# Numpy

In [1]:
# Install Numpy
!pip install numpy

In [2]:
import numpy as np

In [3]:
np.__version__

'1.24.3'

# Array

### Membuat array rank 1 atau ID

In [12]:
a = np.array([0,1,2])
print(type(a))

# Menampilkan dimensi Array
#b = a.shape # outputya = tuples

print(a.ndim) # menghitung dimensi
print(a.shape) # menghitung ukuran dari dimensi misal 2x3
print(a.size) # menghitung banyaknya data

print(a[0])
print(a[1])
print(a[2])

# Mengganti nilai dari array
a[0] = 5
print(a)

<class 'numpy.ndarray'>
1
(3,)
3
0
1
2
[5 1 2]


In [13]:
# Membuat array string
a = np.array(["Jakarta", "Surabaya", "Malang"])
a

array(['Jakarta', 'Surabaya', 'Malang'], dtype='<U8')

### Membuat array rank 2 atau dua dimensi (2D)

In [14]:
arr = np.array([[0,1,2], [3,4,5]])
arr

array([[0, 1, 2],
       [3, 4, 5]])

Mengambil jumlah data dari array dua dimensi

In [15]:
# mengambil jumlah baris dan kolom. contoh = (2, 3)
arr.shape 

(2, 3)

Mengambil data dari array dua dimensi

In [16]:
# mengambil data dari baris ke 1 dan kolom ke 2
a = arr[1, 2]
print(a) # 5

# mengambil data dari baris ke 0 dan kolom ke 1
b = arr[0, 1] 
print(b) # 1


5
1


# NumPy Array

### Membuat array 1 dimensi (1D)

In [17]:
arr1 = np.arange(10) # membuat array 1D secara berurutan
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr2 = np.arange(2, 10, dtype=float) # (start, end) dan mengubah tipe datanya menjadi float
arr2

array([2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr3 = np.arange(2, 3, 0.1) # (start, stop, step)
arr3

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [23]:
arr4 = np.linspace(1., 4., 6) # (start, stop, step)
arr4

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

### Membuat array 2 dimensi (2D)

In [ ]:
# Membuat array dengan 3 baris dan 3 kolom (3x3)
arr1 = np.eye(3)
arr1

In [ ]:
# Membuat array dengan 2 baris dan 4 kolom (2x4)
arr2 = np.eye(2,4)
arr2

In [ ]:
# Mendefinisikan array 2D persegi dengan nilai yang diberikan sepanjang diagonal
arr3 = np.diag([1,2,3])
arr3

In [ ]:
# Mendefinisikan array 2D persegi dengan nilai yang di berikan secara diagonal dimulai dari baris ke 1 kolom ke 3 [0,2]
arr4 = np.diag([1,2,3], 2) 
arr4

In [ ]:
arr5 = np.diag([[2,3], [5,7]]) # mengambil data pertama di baris pertama dan data terakhir di kolom terakhir
arr5

In [24]:
# Matriks Vandermonde
# vander(x, n) atau (baris, jumlah kolom)
# n - 1
arr6 = np.vander([2,3,4], 4)
arr6


array([[ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

##### Cara kerjanya : 

Untuk elemen input 2: <br>
n = 4 <br>
n - 1 = 3 <br>
- 2^3 = 8
- 2^2 = 4
- 2^1 = 2
- 2^0 = 1


Untuk elemen input 3: <br>
- 3^3 = 27
- 3^2 = 9
- 3^1 = 3
- 3^0 = 1

Untuk elemen input 4: <br>
- 4^3 = 64
- 4^2 = 16
- 4^1 = 4
- 4^0 = 1

In [ ]:
# Menggabungkan dengan linspace
np.vander(np.linspace(0, 2, 5), 2)

# artinya 
# vander(x, n)
# vander(np.linspace(start, stop, step), n)

# General ndarray Creation Functions

### Zero Matrix

In [25]:
# Mendefinisikan matriks 2x3 (2 baris, 3 kolom)
# zeros((row, col))
arr1 = np.zeros((2, 3))
arr1

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
### Mendefinisikan array 3D dengan bentuk (2, 3, 2) 
# zeros((layer, row, col))
arr2 = np.zeros((2, 3 , 3))
arr2

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

### One Matrix

In [29]:
# Mendefinisikan matriks 2x3 (2 baris, 3 kolom)
# ones((2, 3))

arr3 = np.ones((2,3))
arr3

array([[1., 1., 1.],
       [1., 1., 1.]])

In [30]:
# Mendefinisikan array 3D dengan bentuk (3, 3, 2) 
# ones((layer, row, col))
arr4 = np.ones((3, 3, 2))
arr4

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

### Custom Matrix Value

In [32]:
# Mendefinisikan matriks full dengan nilai custom
# full((row, col), n)
arr1 = np.full((3, 4), 3)
arr1

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

### Random Matrix

In [36]:
# Mendefinisikan array 3x3 dengan nilai acak
arr1 = np.random.random((3,2))
arr1

array([[0.79208749, 0.88464515],
       [0.65514177, 0.61735866],
       [0.76841493, 0.23150973]])

### Indices

In [39]:
# Array yang dihasilkan oleh np.indices memiliki bentuk (2, 3, 3) yang sesuai dengan dimensi baris, kolom, dan "salinan" dari array asli.
arr = np.indices((4,2))
arr

array([[[0, 0],
        [1, 1],
        [2, 2],
        [3, 3]],

       [[0, 1],
        [0, 1],
        [0, 1],
        [0, 1]]])

### Convert List to Array

In [40]:
# List
arr = [1,2,3]
print(arr)

# Convert to array
arr = np.array([1,2,3])
print(arr)

[1, 2, 3]
[1 2 3]
