# Array Indexing

dapat diindeks menggunakan sintaks standar Python x[obj], di mana x adalah array dan obj pilihannya. Ada berbagai jenis pengindeksan yang tersedia tergantung pada objeknya: pengindeksan dasar, pengindeksan lanjutan, dan akses lapangan

In [ ]:
# Install Numpy
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
np.__version__

## Basic Indexing

### Single Element Indexing


Pengindeksan elemen tunggal berfungsi persis seperti itu untuk rangkaian Python standar lainnya. Ini berbasis 0, dan menerima indeks negatif untuk pengindeksan dari akhir array.

In [ ]:
# Mendefinisikan sebuah array dimulai dari 2 ke 10
arr = np.arange(2, 10)
print(arr)

print(arr[3]) # mengambil index ke 3
print(arr[-2]) # mengambil index dari belakang sebanyak 2 slot

In [ ]:
x = np.arange(10) # array 1 dimensi
print(x)

x.shape = (2, 5) # sekarang x menjadi 2 dimensi (menjadi 2x5)
print(x)

print(x[1,3]) # mengambil index baris ke 1 kolom ke 3 hasilnya 8

print(x[1, -1]) # mengambil index baris ke 1 kolom terakhir index ke (10 - 1) = 9 hasilnya 9

print(x[0]) # hanya mengambil index baris ke 0

print(x[0][2]) # mengambil index baris ke 0 kolom ke 2

### Basic Slicing

In [17]:
arr = np.array([5,6,7,8,9,10,11,12,13])
arr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13])

In [19]:
arr[1:7:2] # [start : stop : step]

array([ 6,  8, 10])

In [22]:
x = np.array([5,6,7,8,9])
x

array([5, 6, 7, 8, 9])

In [23]:
print(x[-2:5])
print(x[-1:1:-1])
print(x[-1:1:1])
print(x[-3:5:1])

[8 9]
[9 8 7]
[]
[7 8 9]


In [26]:
print(x[:4])
print(x[-3:])

[5 6 7 8]
[7 8 9]


### Slicing and Striding

Pengirisan dasar memperluas konsep dasar pemotongan Python ke N dimensi. Pengirisan dasar terjadi ketika obj adalah objek irisan (dibangun dengan notasi start:stop:step di dalam tanda kurung), bilangan bulat, atau tupel objek irisan dan bilangan bulat. Objek elipsis dan sumbu baru juga dapat diselingi dengan objek ini.

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr)

print(arr[2:8]) # (start, stop)

print(arr[1:7:2]) # (start, stop, step)

print(arr[-2:10]) # artinya dari index ke 8 ke 10 - 1

print(arr[5:]) # mengambil index mulai dari 5 dan seterusnya

print(arr[:5]) # mengambil index mulai dari awal sampai index ke 5 - 1

In [ ]:
arr1 = np.array([[[1],[2],[3]], [[4],[5],[6]]])
print(arr1)

print(arr1.shape)

print(arr1[1:2])

### Dimensional Indexing Tools

Ada beberapa alat untuk memfasilitasi pencocokan bentuk array dengan ekspresi dan tugas dengan mudah.

Ellipsis bertambah hingga jumlah : objek yang dibutuhkan tupel seleksi untuk mengindeks semua dimensi. Dalam kebanyakan kasus, ini berarti panjang tupel pilihan yang diperluas adalah x.ndim. Mungkin hanya ada satu elipsis. Dari contoh di atas:

In [27]:
x = np.array([[[1],[2],[3]], [[4],[5],[6]]])
x[..., 0]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
x[:, :, 0]

## Field Access

In [ ]:
x = np.zeros((3,3), dtype=[('a' , np.int32), ('b', np.float64, (3,3))])

print("x[a].shape : ", x['a'].shape)
print("x[a].dtype : ", x['a'].dtype)

print("x[b].shape : ", x['b'].shape)
print("x[b].dtype : ", x['b'].dtype)

In [ ]:
x

In [ ]:
x['a']

In [ ]:
x['b']

In [ ]:
y = np.zeros((1,2), dtype=[('a', np.int32), ('b', np.float64, (2,3))])

print("y['a'].shape : ", y['a'].shape)
print("y['a'].dtype : ", y['a'].dtype)

print("y['b'].shape : ", y['b'].shape)
print("y['b'].dtype : ", y['b'].shape)

In [ ]:
y

In [ ]:
y.shape

## Advanced Indexing

In [30]:
arr = np.array([[1,2], [3,4]])
arr

array([[1, 2],
       [3, 4]])

In [31]:
arr.shape

(2, 2)

In [32]:
arr[0], arr[1]

(array([1, 2]), array([3, 4]))

In [33]:
arr[1,0]

3

In [34]:
arr[[0,1]]

array([[1, 2],
       [3, 4]])

In [35]:
arr[[1,0]]

array([[3, 4],
       [1, 2]])

In [36]:
arr[[1,1]]

array([[3, 4],
       [3, 4]])

In [37]:
print(arr[[0,1], [0,1]])

print(np.array([arr[0, 0], arr[1,1]]))

[1 4]
[1 4]


In [40]:
arr[[1, 0], [1,1]], np.array([arr[1,1], arr[1,1]])

(array([4, 2]), array([4, 4]))

In [41]:
print(arr[[0,0], [1,1]])

print(np.array([arr[0,1], arr[0,1]]))

[2 2]
[2 2]


In [45]:
a = np.array([[1,2], [3,4], [5,6]])

print(a)

print(a > 2)

print(a[a > 2])

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
