# I/O File

In [1]:
import numpy as np

In [2]:
np.__version__

'1.24.3'

## Random Array

In [3]:
a = np.random.random((3,3))
b = np.random.random((3,3))

In [4]:
a, b

(array([[0.21921593, 0.22015264, 0.71528797],
        [0.83144895, 0.34068593, 0.36919915],
        [0.71065756, 0.98905828, 0.27400433]]),
 array([[0.14473839, 0.20266748, 0.94174501],
        [0.12695873, 0.13165293, 0.58510136],
        [0.54801321, 0.02936487, 0.0399627 ]]))

## Save File

In [5]:
# Simpan file dengan satu data
np.save('my_array', a)

print('File berhasil di simpan')

File berhasil di simpan


In [6]:
# Menyimpan file dengan data lebih dari satu
np.savez('array.npz', a, b, a, a)

print('File berhasil di simpan')

File berhasil di simpan


## Load File

In [7]:
# Load file dengan satu data
a1 = np.load('my_array.npy')
a1

array([[0.21921593, 0.22015264, 0.71528797],
       [0.83144895, 0.34068593, 0.36919915],
       [0.71065756, 0.98905828, 0.27400433]])

In [8]:
# Load file dengan data lebih dari satu
a2 = np.load('array.npz')

print(a2.files)

['arr_0', 'arr_1', 'arr_2', 'arr_3']


In [12]:
print(a2['arr_0'])
print(a2['arr_1'])
print(a2['arr_2'])
print(a2['arr_3'])

[[0.21921593 0.22015264 0.71528797]
 [0.83144895 0.34068593 0.36919915]
 [0.71065756 0.98905828 0.27400433]]
[[0.14473839 0.20266748 0.94174501]
 [0.12695873 0.13165293 0.58510136]
 [0.54801321 0.02936487 0.0399627 ]]
[[0.21921593 0.22015264 0.71528797]
 [0.83144895 0.34068593 0.36919915]
 [0.71065756 0.98905828 0.27400433]]
[[0.21921593 0.22015264 0.71528797]
 [0.83144895 0.34068593 0.36919915]
 [0.71065756 0.98905828 0.27400433]]


In [13]:
# Simpan dengan nama array
np.savez('array2.npz', a = a, b = b)

In [15]:
# Load data 
npz = np.load('array2.npz')
npz.files

['a', 'b']

In [18]:
npz['a']

array([[0.21921593, 0.22015264, 0.71528797],
       [0.83144895, 0.34068593, 0.36919915],
       [0.71065756, 0.98905828, 0.27400433]])

In [19]:
npz['b']

array([[0.14473839, 0.20266748, 0.94174501],
       [0.12695873, 0.13165293, 0.58510136],
       [0.54801321, 0.02936487, 0.0399627 ]])