# Numpy

Numpy adalah library utama untuk komputasi ilmiah dengan Python. Ini menyediakan objek array multidimensi kinerja tinggi, dan alat untuk bekerja dengan array ini. Ini adalah penerus package Numerik. Pada tahun 2005, Travis Oliphant menciptakan NumPy dengan menggabungkan fitur Numarray yang bersaing ke dalam Numerik, dengan modifikasi ekstensif. 

Topik bahasan meliput:

* Arrays
* Tipe Data
* Array indexing
* Indexing Lanjut
* Operasi Matematika Pada Array
* Broadcasting
* I/O Files


Untuk menggunakan Numpy, kita harus install `numpy` package:
``` 
pip install numpy 
pip3 install numpy 

```


In [1]:
# install melalui Jupyter Notebook
!pip install numpy

In [2]:
import numpy as np

In [3]:
np.__version__

'1.19.5'

## Arrays

Cara membuat array pada numpy

In [4]:
# Membuat array dengan rank 1
a = np.array([0, 1, 2]) 
print(type(a))

# tampilkan dimensi array
b = a.shape # tuples

print(a.shape) 
print(a[0])
print(a[1])
print(a[2])

# Mengganti nilai dari element array
a[0] = 5                 
print(a)                  

<class 'numpy.ndarray'>
(3,)
0
1
2
[5 1 2]


In [5]:
b = np.array(['jakarta','bogor','bekasi'])
b

array(['jakarta', 'bogor', 'bekasi'], dtype='<U7')

In [6]:
# Membuat array dengan rank 2
b = np.array([[0,1,2],[3,4,5]])  
print(b.shape)                     
print(b)
print(b[0, 0], b[0, 1], b[1, 0])   

(2, 3)
[[0 1 2]
 [3 4 5]]
0 1 3


In [8]:
print(b.shape)                   
print(b[0, 0], b[1, 1], b[1, 0])

(2, 3)
0 4 3


In [9]:
c = np.array([123,'bogor',4.56])
c

array(['123', 'bogor', '4.56'], dtype='<U11')

In [10]:
type(c)

numpy.ndarray

### Membuat NumPy array

In [11]:
# Buat array 3x3 dengan semua nilai 0
a = np.zeros((3,3)) 
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
np.zeros((2,3)) 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
# Buat array 2x2 dengan semua nilai 0
b = np.ones((2,2),dtype=np.int64)  
print(b)
print(b.dtype)

[[1 1]
 [1 1]]
int64


In [14]:
# Buat array 3x3 dengan semua nilai konstan
c = np.full((3,3), 8) 
print(c) 

[[8 8 8]
 [8 8 8]
 [8 8 8]]


In [15]:
c = np.full((5,2), 1.3) 
print(c) 

[[1.3 1.3]
 [1.3 1.3]
 [1.3 1.3]
 [1.3 1.3]
 [1.3 1.3]]


In [16]:
# Buat array 3x3 dengan semua nilai acak
d = np.random.random((3,3)) 
print(d)

[[0.78050648 0.15491275 0.70164983]
 [0.49712329 0.6479866  0.57747135]
 [0.49176867 0.70398338 0.7642652 ]]


In [17]:
# Buat 3x3 identity matrix
e = np.eye(3)        
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
np.eye(4) 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
# Konversi list ke array
f = np.array([2, 3, 1, 0]) 
print(f)

[2 3 1 0]


In [20]:
# arange() akan membuat array dengan nilai yang bertambah secara teratur
g = np.arange(15)
print(g)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [21]:
# gabungan tuple dan list
h = np.array([[0, 1,2.0],[0,0,0],(1+1j,3.,2.)])                           
print(h)

[[0.+0.j 1.+0.j 2.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [1.+1.j 3.+0.j 2.+0.j]]


In [22]:
# membuat array dengan float data type 
i = np.arange(1, 8, dtype=np.float64)
print(i)

[1. 2. 3. 4. 5. 6. 7.]


In [23]:
# linspace() akan membuat array dengan jumlah item tertentu yang 
# berjarak sama antara nilai awal dan akhir yang ditentukan
j = np.linspace(2., 4., 5)
print(j)

[2.  2.5 3.  3.5 4. ]


In [24]:
j = np.linspace(1, 10, 20)
print(j)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [25]:
# indices () akan membuat satu set array yang ditumpuk sebagai array berdimensi satu lebih tinggi, 
# satu per dimensi dengan masing-masing mewakili variasi dalam dimensi itu

k = np.indices((2,2))
print(k)

[[[0 0]
  [1 1]]

 [[0 1]
  [0 1]]]


In [26]:
k = np.indices((2,3))
k

array([[[0, 0, 0],
        [1, 1, 1]],

       [[0, 1, 2],
        [0, 1, 2]]])

## Tipe Data

Array adalah kumpulan item dari tipe data yang sama, NumPy mendukung dan menyediakan fungsi bawaan untuk membangun array dengan argumen opsional untuk secara eksplisit menentukan tipe data yang diperlukan.

In [27]:
# Membiarkan numpy memilih tipe data
x = np.array([0, 1])  
y = np.array([2.0, 3.0])  

# Memaksa tipe data
z = np.array([5, 6], dtype=np.int64)  

print(x.dtype, y.dtype, z.dtype)

int32 float64 int64


Info selengkapnya [documentation](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

## Array Indexing

Numpy menawarkan beberapa cara untuk mengindeks ke dalam array. Sintaks standar Python x[obj] dapat digunakan untuk mengindeks NumPyarray, di mana x adalah array dan obj pilihan.

Ada tiga jenis pengindeksan yang tersedia
* Field access
* Basic slicing
* Advanced indexing


### Field Access

Jika objek ndarray adalah array terstruktur, bidang array dapat diakses dengan mengindeks array dengan string, seperti dictionary. 

Pengindeksan x['field-name'] mengembalikan tampilan baru ke array, yang bentuknya sama dengan x, kecuali jika bidangnya adalah sub-array, tetapi bertipe data x.dtype['field-name'] dan hanya berisi bagian dari data di bidang yang ditentukan.

In [28]:
x = np.zeros((3,3), dtype=[('a', np.int32), ('b', np.float64, (3,3))])
print("x['a'].shape: ",x['a'].shape)
print("x['a'].dtype: ", x['a'].dtype)

print("x['b'].shape: ", x['b'].shape)
print("x['b'].dtype: ", x['b'].dtype)

x['a'].shape:  (3, 3)
x['a'].dtype:  int32
x['b'].shape:  (3, 3, 3, 3)
x['b'].dtype:  float64


In [29]:
x

array([[(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]),
        (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]),
        (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])],
       [(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]),
        (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]),
        (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])],
       [(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]),
        (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]),
        (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])]],
      dtype=[('a', '<i4'), ('b', '<f8', (3, 3))])

In [30]:
x['a']

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [31]:
x['b']

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

In [32]:
x = np.zeros((1,2), dtype=[('a', np.int32), ('b', np.float64, (2,3))])
print("x['a'].shape: ",x['a'].shape)
print("x['a'].dtype: ", x['a'].dtype)

print("x['b'].shape: ", x['b'].shape)
print("x['b'].dtype: ", x['b'].dtype)

x['a'].shape:  (1, 2)
x['a'].dtype:  int32
x['b'].shape:  (1, 2, 2, 3)
x['b'].dtype:  float64


In [33]:
x

array([[(0, [[0., 0., 0.], [0., 0., 0.]]),
        (0, [[0., 0., 0.], [0., 0., 0.]])]],
      dtype=[('a', '<i4'), ('b', '<f8', (2, 3))])

In [34]:
x.shape

(1, 2)

### Basic Slicing

Array NumPy dapat diiris, mirip dengan list. Anda harus menentukan irisan untuk setiap dimensi array karena array mungkin multidimensi. 

Sintak irisan dasar adalah i:j:k di mana i adalah indeks awal, j adalah indeks penghentian, dan k adalah langkah dan k tidak sama dengan 0. Ini memilih elemen m dalam dimensi yang sesuai, dengan nilai indeks i, i + k, ...,i + (m - 1) k dimana m = q + (r tidak sama dengan 0) dan q dan r adalah hasil bagi dan sisa yang diperoleh dengan membagi j - i dengan k: j - i = qk + r, sehingga i + (m - 1) k < j.


In [35]:
x = np.array([5, 6, 7, 8, 9])
x

array([5, 6, 7, 8, 9])

In [36]:
x[1:7:2]

array([6, 8])

In [37]:
x[2:8:1]

array([7, 8, 9])

In [38]:
x[1:4]

array([6, 7, 8])

k negatif membuat loncatan menuju indeks yang lebih kecil. i dan j negatif diinterpretasikan sebagai n + i dan n + j di mana n adalah jumlah elemen dalam dimensi yang sesuai.

In [39]:
x

array([5, 6, 7, 8, 9])

In [40]:
print(x[-2:5])
print(x[-1:1:-1])
print(x[-1:1:1])
print(x[-3:5:1])

[8 9]
[9 8 7]
[]
[7 8 9]


In [41]:
print(x[-1:2:-1])
print(x[-1:2:1])

[9 8]
[]


In [42]:
print(x[-1:-5:-1])

[9 8 7 6]


Jika n adalah jumlah item dalam dimensi yang diiris. Kemudian jika i tidak diberikan maka defaultnya adalah 0 untuk k > 0 dan n - 1 untuk k < 0 . Jika j tidak diberikan defaultnya adalah n untuk k > 0 dan -1 untuk k < 0 . Jika k tidak diberikan, defaultnya adalah 1. Perhatikan bahwa :: sama dengan : dan berarti pilih semua indeks di sepanjang sumbu ini.

In [43]:
x[4:]

array([9])

In [44]:
x[-3:]

array([7, 8, 9])

Jika jumlah objek dalam tupel pemilihan kurang dari N , maka : diasumsikan untuk setiap dimensi berikutnya.

In [45]:
y = np.array([[[0],[1],[2],[3]], [[4],[5],[6]],[7]],  dtype=object)
print("Shape of y: ", y.shape)
y[1:3]

Shape of y:  (3,)


array([list([[4], [5], [6]]), list([7])], dtype=object)

In [46]:
y

array([list([[0], [1], [2], [3]]), list([[4], [5], [6]]), list([7])],
      dtype=object)

Elipsis diperluas ke jumlah : objek yang dibutuhkan untuk membuat tupel seleksi dengan panjang yang sama dengan x.ndim. Mungkin hanya ada satu elipsis yang ada.

In [47]:
x

array([5, 6, 7, 8, 9])

In [48]:
x[...,0]

array(5)

In [49]:
x[...,1]

array(6)

In [50]:
x[...,3]

array(8)

In [51]:
x[...,1:]

array([6, 7, 8, 9])

In [52]:
x[1,...]

array(6)

In [53]:
x[1:,...]

array([6, 7, 8, 9])

In [54]:
# Buat rank 2 array dengan ukuran (3, 4)
a = np.array([[5,6,7,8], [1,2,3,4], [9,10,11,12]])
print("Array a: ", a)

# Gunakan slicing untuk mengeluarkan subarray yang terdiri dari 2 baris pertama dan 
# kolom 1 dan 2; b adalah larik bentuk berikut (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print("Array b: ", b)

Array a:  [[ 5  6  7  8]
 [ 1  2  3  4]
 [ 9 10 11 12]]
Array b:  [[6 7]
 [2 3]]


Sepotong larik hanyalah tampilan ke dalam data yang sama, jadi modifikasi apa pun akan mengubah larik asli.

In [56]:
print( a[0, 1])  
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1]) 

77
77


Array baris tengah dapat diakses dengan dua cara.
1. Irisan bersama dengan pengindeksan bilangan bulat akan menghasilkan serangkaian peringkat yang lebih rendah.
2. Hanya menggunakan irisan akan menghasilkan array peringkat yang sama.

In [57]:
# rank 2 array dengan ukuran (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print (a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Dua cara mengakses data di baris tengah array.
Pencampuran pengindeksan integer dengan irisan menghasilkan array peringkat yang lebih rendah,
saat hanya menggunakan irisan menghasilkan larik dengan peringkat yang sama dengan
susunan asli:

In [58]:
row_r1 = a[1, :]    # Rank 1 tampilan dari baris kedua a  
row_r2 = a[1:2, :]  # Rank 2 tampilan dari baris kedua a
row_r3 = a[[1], :]  # Rank 2 tampilan dari baris kedua a
print(row_r1, row_r1.shape) 
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [59]:
# Kita dapat membuat perbedaan yang sama ketika mengakses kolom dari sebuah array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [60]:
a[:, 1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [61]:
row_r1 = a[2:3, :] 
print(row_r1, row_r1.shape) 
col_r2 = a[:, 2:3]
print(col_r2, col_r2.shape)

[[ 9 10 11 12]] (1, 4)
[[ 3]
 [ 7]
 [11]] (3, 1)


## Indexing Lanjut
Slicing array dengan index

Integer array indexing: Saat Anda mengindeks ke array numpy menggunakan slicing, tampilan array yang dihasilkan akan selalu menjadi subarray dari array asli. Sebaliknya, pengindeksan array iInteger memungkinkan Anda untuk membuat array acak arbitrer menggunakan data dari array lain.

In [62]:
a = np.array([[1,2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [63]:
a.shape

(2, 2)

In [64]:
a[0], a[1]

(array([1, 2]), array([3, 4]))

In [65]:
a[1,0]

3

In [66]:
a[[0,1]]

array([[1, 2],
       [3, 4]])

In [67]:
a[[1,0]]

array([[3, 4],
       [1, 2]])

In [68]:
a[[1,1]]

array([[3, 4],
       [3, 4]])

In [69]:
# Contoh pengindeksan array integer.
# Array yang dikembalikan akan memiliki bentuk (2,) dan
print(a[[0, 1], [0, 1]])

# Contoh pengindeksan array integer di atas setara dengan ini:
print(np.array([a[0, 0], a[1, 1]]))

[1 4]
[1 4]


In [72]:
a[[1, 0], [1, 1]],  np.array([a[1, 1], a[1, 1]])

(array([4, 2]), array([4, 4]))

In [73]:
# Saat menggunakan pengindeksan array integer, 
#Anda dapat menggunakan kembali elemen yang sama dari array sumber:
print(a[[0, 0], [1, 1]])

# Kesamaan dengan integer array indexing
print(np.array([a[0, 1], a[0, 1]]))

[2 2]
[2 2]


Boolean array indexing: Ini berguna untuk memilih elemen acak dari larik, yang sering digunakan untuk memfilter elemen yang memenuhi kondisi tertentu.

In [75]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)
# Cari element yang lebih besar dari 2
print (a > 2)  

# untuk mendapatkan nilainya
print (a[a > 2])

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]


## Operasi Matematika Pada Array

Fungsi matematika dasar tersedia sebagai operator dan juga sebagai fungsi di NumPy. Ini beroperasi secara elemen pada array.

In [76]:
x = np.array([[1,2],[3,4],[5,6]])
y = np.array([[7,8],[9,10],[11,12]])

# penjumlahan
print(x + y)
print(np.add(x, y))

[[ 8 10]
 [12 14]
 [16 18]]
[[ 8 10]
 [12 14]
 [16 18]]


In [77]:
# pengurangan
print(x - y)
print(np.subtract(x, y))

[[-6 -6]
 [-6 -6]
 [-6 -6]]
[[-6 -6]
 [-6 -6]
 [-6 -6]]


In [78]:
# perkalian
print (x * y)
print (np.multiply(x, y))

[[ 7 16]
 [27 40]
 [55 72]]
[[ 7 16]
 [27 40]
 [55 72]]


In [79]:
# pembagian
print (x / y)
print (np.divide(x, y))

[[0.14285714 0.25      ]
 [0.33333333 0.4       ]
 [0.45454545 0.5       ]]
[[0.14285714 0.25      ]
 [0.33333333 0.4       ]
 [0.45454545 0.5       ]]


In [80]:
# akar kuadrat
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]
 [2.23606798 2.44948974]]


Kita dapat menggunakan fungsi "dot" untuk menghitung perkalian dalam vektor atau mengalikan matriks atau mengalikan vektor dengan matriks

In [81]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

a = np.array([9,10])
b = np.array([11, 12])

# perkalian dot
print(a.dot(b))
print (np.dot(a, b))

219
219


In [82]:
# perkalian dot. Keduanya menghasilkan rank 1 array [29 67]
print (x.dot(a))
print (np.dot(x, a))

[29 67]
[29 67]


In [83]:
x.shape, y.shape, a.shape, b.shape

((2, 2), (2, 2), (2,), (2,))

In [84]:
# perkalian dot. Keduanya menghasilkan rank 2 array
print (x.dot(y))
print (np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Numpy menyediakan banyak fungsi yang berguna untuk melakukan perhitungan pada array, salah satu yang paling berguna adalah `sum`:

In [85]:
x = np.array([[1,2],[3,4]])

# Jumlah semua element
print (np.sum(x))  
# Jumlah masing-masing kolom
print (np.sum(x, axis=0))  
# Jumlah masing-masing baris
print (np.sum(x, axis=1))  

10
[4 6]
[3 7]


Transpose adalah salah satu operasi umum yang sering dilakukan pada matriks, yang dapat dicapai dengan menggunakan atribut T dari objek array.

In [86]:
print (x)
print (x.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [87]:
v = np.array([1,2,3])
print (v) 
print (v.T)

[1 2 3]
[1 2 3]


## Broadcasting


Broadcasting memungkinkan operasi aritmatika dilakukan antara array berbentuk berbeda. Mari kita lihat contoh sederhana menambahkan vektor konstan ke setiap baris matriks.

In [88]:
# buat matrik
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
# buat vektor
v = np.array([1, 0, 1])

print(a.shape, v.shape)

# buat matrik kosong dengan ukuran yang sama dengan matrik a
b = np.empty_like(a)   

# Tambah vektor v ke masing-masing baris matrik
for i in range(3):
    b[i, :] = a[i, :] + v

print(b)

(3, 3) (3,)
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]


Jika kita harus melakukan operasi di atas pada matriks besar melalui loop di Python bisa menjadi lambat. Mari kita lihat pendekatan alternatif.

In [89]:
# Stack 3 salinan dari v di atas satu sama lain
vv = np.tile(v, (3, 1))  
print (vv)

[[1 0 1]
 [1 0 1]
 [1 0 1]]


In [90]:
# tambah x dan vv 
b = a + vv  
print (b)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]


Numpy broadcasting memungkinkan kita untuk melakukan perhitungan ini tanpa benar-benar membuat banyak salinan v

In [91]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
v = np.array([1, 0, 1])

# Tambah v ke masing2x baris dengan broadcasting
b = a + v  
print (b)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]


Mari kita lihat beberapa aplikasi broadcasting:

In [92]:
# Hitung hasil kali luar vektor
# v dengan ukuran (3,)
v = np.array([1,2,3])
# w dengan ukuran (2,)
w = np.array([4,5]) 

# Untuk menghitung produk luar, pertama-tama kita bentuk ulang v menjadi 
# vektor kolom bentuk (3, 1); kita kemudian dapat broadcast terhadap w 
# untuk menghasilkan output bentuk (3, 2), yang merupakan produk luar dari v dan w:

print (np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [93]:
# Add a vector to each row of a matrix
# Tambahkan vektor ke setiap baris matrik
x = np.array([[1,2,3], [4,5,6]])

# x memiliki bentuk (2, 3) dan v memiliki bentuk (3,) sehingga broadcast ke (2, 3)

print (x + v)

[[2 4 6]
 [5 7 9]]


In [94]:
# Tambahkan vektor ke setiap kolom matriks
# x berbentuk (2, 3) dan w berbentuk (2,).
# Jika kita transpose x maka x memiliki bentuk (3, 2) dan 
# dapat broadcast ke w untuk menghasilkan hasil bentuk (3, 2); 
# mentranspos hasil ini menghasilkan hasil akhir bentuk (2, 3) 
# yang merupakan matriks x dengan vektor w ditambahkan ke setiap kolom

print ((x.T + w).T)

[[ 5  6  7]
 [ 9 10 11]]


In [95]:
# Solusi lain adalah dengan membentuk ulang w menjadi vektor baris bentuk (2, 1);
# kemudian kita dapat broadcast secara langsung terhadap x 
# untuk menghasilkan keluaran yang sama.

print (x + np.reshape(w, (2, 1)))

[[ 5  6  7]
 [ 9 10 11]]


In [96]:
# Kalikan matrik dengan konstanta:
# x berbentuk (2, 3). Numpy memperlakukan skalar sebagai array bentuk ();
# ini dapat di broadcast bersama untuk membentuk (2, 3), menghasilkan larik berikut:

print (x * 2)

[[ 2  4  6]
 [ 8 10 12]]


Broadcasting biasanya membuat kode Anda lebih ringkas dan lebih cepat, jadi Anda harus berusaha untuk menggunakannya jika memungkinkan.

Informasi selengkapnya [numpy reference](http://docs.scipy.org/doc/numpy/reference/) 

## I/O File

In [97]:
a = np.random.random((3,3)) 
b = np.random.random((3,3)) 
print(a)
print(b)

[[0.32506257 0.72516694 0.86293972]
 [0.19042731 0.49191994 0.92660087]
 [0.93161258 0.31801449 0.97828995]]
[[0.43096621 0.37369919 0.45970859]
 [0.15318157 0.96518202 0.9967589 ]
 [0.31279254 0.24309633 0.0859656 ]]


In [98]:
# simpan file
np.save('my_array', a)
np.savez('array.npz', a, b,a,a)
print('saved data into files')

saved data into files


In [99]:
# load file
a1 = np.load('my_array.npy')
a1

array([[0.32506257, 0.72516694, 0.86293972],
       [0.19042731, 0.49191994, 0.92660087],
       [0.93161258, 0.31801449, 0.97828995]])

In [100]:
npz = np.load('array.npz')
print(npz.files)


['arr_0', 'arr_1', 'arr_2', 'arr_3']


In [101]:
print(npz['arr_0'])
print(npz['arr_1'])

[[0.32506257 0.72516694 0.86293972]
 [0.19042731 0.49191994 0.92660087]
 [0.93161258 0.31801449 0.97828995]]
[[0.43096621 0.37369919 0.45970859]
 [0.15318157 0.96518202 0.9967589 ]
 [0.31279254 0.24309633 0.0859656 ]]


In [102]:
# simpan dengan nama array
np.savez('array2.npz', a=a, b=b)
npz2 = np.load('array2.npz')
print(npz2['a'])
print(npz2['b'])

[[0.32506257 0.72516694 0.86293972]
 [0.19042731 0.49191994 0.92660087]
 [0.93161258 0.31801449 0.97828995]]
[[0.43096621 0.37369919 0.45970859]
 [0.15318157 0.96518202 0.9967589 ]
 [0.31279254 0.24309633 0.0859656 ]]
